### ISSUE TITLE
Error when select an item in box

### ISSUE THREAD

**Issue by dbirkheuer** [kholifanalfon/bs_flutter#1]
Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:54424/dart_sdk.js:5080:11)
    at Object.nullCheck (http://localhost:54424/dart_sdk.js:5399:30)
    at http://localhost:54424/packages/bs_flutter_selectbox/src/utils/bs_serverside.dart.lib.js:1556:50
    at http://localhost:54424/dart_sdk.js:34997:33
    at internalCallback (http://localhost:54424/dart_sdk.js:26685:11)

My code:

![image](https://user-images.githubusercontent.com/33560861/182228211-4152dc35-48e5-4cf0-9b92-6365ddf0603d.png)

Error line:

![image](https://user-images.githubusercontent.com/33560861/182228293-b19fd434-30c8-4955-aa0e-ae534d017efa.png)

Can help?

**Comment by huahouye** [comment]
Maybe override dependency can help.

```
dependency_overrides: 
  bs_flutter_selectbox:
    # path: ../../bs_flutter_selectbox
    git: 
      url: https://github.com/kholifanalfon/bs_flutter_selectbox.git
      ref: 959aa30
```
